[Global]
  CheckNewVersion = false
  SendAnonymousUsage = false

[EntryPoints]
  [EntryPoints.http]
    Address = ":80"
  [EntryPoints.https]
    Address = ":443"

[providers.docker]
  exposedByDefault = false # Traefik va ignorer les containers qui n'ont pas le label "traefik.enable=true"
  network = "proxy" # Limite le scope de Traefik au network docker "proxy"

[providers.file]
  directory = "/etc/traefik/config"
  watch = true

[api]
  dashboard = true # active le dashboard et l'api

[metrics]
  [metrics.prometheus]
    manualRouting = true
